### ISSUE TITLE
KDE Wayland Doesn't Provide Way To Pick Video Source

### ISSUE THREAD

**Issue by Hatsune-Cthulhu** [maltejur/discord-screenaudio#191]
When trying to start a stream on KDE Wayland there's no option choose a video source, and clicking start stream just seams to do nothing other than spam the following line into the console:
```
[userscript] Did not find 'discord-screenaudio-virtmic', trying again in 100ms
```

Seen other users state that it's caused by there being no default input, this is not the case for me as I always have a microphone plugged in and the application works fine under X11.

I also get this on app startup:
```
[discord] Error
[discord]     at Function.createFromInputFallback (https://discord.com/assets/25e6fde2b425fd033e23.js:3144:330)
[discord]     at Un (https://discord.com/assets/25e6fde2b425fd033e23.js:3170:696)
[discord]     at Kn (https://discord.com/assets/25e6fde2b425fd033e23.js:3173:356)
[discord]     at Hn (https://discord.com/assets/25e6fde2b425fd033e23.js:3173:199)
[discord]     at Yn (https://discord.com/assets/25e6fde2b425fd033e23.js:3172:886)
[discord]     at Zn (https://discord.com/assets/25e6fde2b425fd033e23.js:3173:697)
[discord]     at Wn (https://discord.com/assets/25e6fde2b425fd033e23.js:3173:731)
[discord]     at i (https://discord.com/assets/25e6fde2b425fd033e23.js:3140:961)
[discord]     at Object.408481 (https://discord.com/assets/989d90c4c7660b499fcc.js:21:346)
[discord]     at l (https://discord.com/assets/34400d96c7984f25ff52.js:1:154)
[discord]     at Object.558820 (https://discord.com/assets/989d90c4c7660b499fcc.js:14:338)
[discord]     at l (https://discord.com/assets/34400d96c7984f25ff52.js:1:154)
[discord]     at Object.308739 (https://discord.com/assets/989d90c4c7660b499fcc.js:2:331)
[discord]     at l (https://discord.com/assets/34400d96c7984f25ff52.js:1:154)
[discord]     at Object.173242 (https://discord.com/assets/bff3b9d23581be4f6ff9.js:408:232)
[discord]     at l (https://discord.com/assets/34400d96c7984f25ff52.js:1:154)
[discord]     at Module.947226 (https://discord.com/assets/0671ab97ed9c48a29f27.js:37:174)
[discord]     at Function.l (https://discord.com/assets/34400d96c7984f25ff52.js:1:154)
```

Any help would be appreciated because I don't want to switch back to X11 due to frame pacing issues when gaming

**Comment by SebastianMeinberger** [comment]
Streaming on kwin/wayland is definitely possible. To my knowledge it requires the following components:

1. PipeWire (So no PulseAudio or alsa setup)
2. pipewire-v4l2 (not 100% sure on that one, but installing pipewire-pulse, pipewire-alsa, pipewire-audio and pipewire-v4l2 is a good idea anyway for a normal setup)
3. WirePlumber (To my knowledge plasma still uses pipewire-media-session, but replacing it should be handled automatically by your package manager when you install wireplumber)
4. xdg-desktop-portal-kde (and of course xdg-desktop-portal, but that should be installed as dependency by your pm)
5. polkit and polkit-kde-agent

When all this is installed, it should work without any further configuration.

![image](https://github.com/maltejur/discord-screenaudio/assets/59895994/3ad67e52-8e62-4ed5-8819-7637b2ca4993)

When this doesn't help, you need to provide more information about your system (a good idea anyway)
