### ISSUE TITLE
Endless loading screen after a few seconds

### ISSUE THREAD

**Issue by Lolotronop** [maltejur/discord-screenaudio#197]
Had this problem both with flatpak and AUR versions of discord-screenaudio, normal discord flatpak and web version work as usual
I open Discord, it loads messages in my last opened channel (or dm), and after a few seconds I'm met with the same old loading screen (that also has a note on streaming issues on Windows with NVIDIA, lol what a meme). Sometimes the loading screen did close again, but I couldn't send or receive messages (altho dm notifications still appeared? this is weird) and guild members didn't load.
Logs below seem to suggest that it tries to connect to the Discord's websocket and can't for some reason, and this exact sequence just repeats endlessly. This might be a discord issue tho
There are also A LOT of `[userscript] Cannot locate Mute/Deafen/Settings button container` lines in the logs, might want to stop logging that constantly

```
[discord] [GatewaySocket] [CONNECTED] wss://gateway-us-east1-d.discord.gg/?encoding=json&v=9&compress=zlib-stream in 506 ms
[discord] [ConnectionStore] handleIdentify called [object Object]
[discord] [GatewaySocket] Setting connection state to IDENTIFYING
[discord] [GatewaySocket] [IDENTIFY]
[discord] [GatewaySocket] [HELLO] via
[discord] gateway-prd-us-east1-d-df49: 0, heartbeat interval: 41250, took 512 ms
[discord] [ConnectionStore] Dispatched INITIAL_GUILD [CENSORED, currently opened guild ID was there]
[discord] [GatewaySocket] resetSocketOnError TypeError: Object.hasOwn is not a function
[discord]     at Function.asBigFlag (https://discord.com/assets/c2ed574fea87e62d7d97.js:1:986467)
[discord]     at j.canBasicChannel (https://discord.com/assets/c2ed574fea87e62d7d97.js:1:819245)
[discord]     at https://discord.com/assets/b8f7ac37ee6bd14069da.js:1:9850
[discord]     at z (https://discord.com/assets/b8f7ac37ee6bd14069da.js:1:10122)
[discord]     at Z (https://discord.com/assets/b8f7ac37ee6bd14069da.js:1:11478)
[discord]     at https://discord.com/assets/3761a6fb12b09e0724b2.js:1:900919
[discord]     at https://discord.com/assets/3761a6fb12b09e0724b2.js:1:907154
[discord]     at m._dispatch (https://discord.com/assets/3761a6fb12b09e0724b2.js:1:900911)
[discord]     at https://discord.com/assets/3761a6fb12b09e0724b2.js:1:900481
[discord]     at s.log (https://discord.com/assets/3761a6fb12b09e0724b2.js:1:907087)
[discord] [GatewaySocket] [RESET] (true, 1000, Resetting socket due to error.)
[discord] [Flux] Dispatching CONNECTION_CLOSED
[discord] [AuthenticationStore] handleConnectionClosed called with code 1000. [object Object]
[discord] [ConnectionStore] connection closed dispatched
[discord] [GatewaySocket] Setting connection state to WILL_RECONNECT
[discord] Uncaught TypeError: Object.hasOwn is not a function
```

**Comment by hizani** [comment]
same

**Comment by hizani** [comment]
The problem occurs with AUR and Flatpak version, so it's not about unstable drivers

**Comment by TheMenko** [comment]
same issue

**Comment by gjedlicska** [comment]
i have the same issue on a flatpak version
