### ISSUE TITLE
discord-screenaudio stopped working - GUI not loading correctly

### ISSUE THREAD

**Issue by xxhinotorixx** [maltejur/discord-screenaudio#202]
### Discussed in https://github.com/maltejur/discord-screenaudio/discussions/201

<div type='discussions-op-text'>

<sup>Originally posted by **xxhinotorixx** October 26, 2023</sup>
Hi everyone!

Has discord-screenaudio stopped working for anyone else?
Since a day or two the GUI seems not to be loaded correctly.
When I run discord-screenaudio through the terminal, it returns the following:

`[discord] [GatewaySocket] Setting connection state to SESSION_ESTABLISHED
[discord] [Flux] Dispatching CONNECTION_OPEN
[discord] [AuthenticationStore] handleConnectionOpen called [object Object]
[discord] [DatabaseManager] removing database (user: 339498780498067477, database: null)
[discord] [DatabaseManager] added database (339498780498067477 → null)
[discord] [GatewaySocket] Updating resume url to wss://gateway-us-east1-d.discord.gg
[discord] [GatewaySocket] resetSocketOnError TypeError: Object.hasOwn is not a function
[discord]     at Function.asBigFlag (https://discord.com/assets/2d60acee3dd6d8a63c76.js:1:998560)
[discord]     at j.canBasicChannel (https://discord.com/assets/2d60acee3dd6d8a63c76.js:1:824737)
[discord]     at https://discord.com/assets/b8f7ac37ee6bd14069da.js:1:9850
[discord]     at z (https://discord.com/assets/b8f7ac37ee6bd14069da.js:1:10122)
[discord]     at X (https://discord.com/assets/b8f7ac37ee6bd14069da.js:1:11413)
[discord]     at https://discord.com/assets/e8fd2221603a9472ac4a.js:1:900919
[discord]     at https://discord.com/assets/e8fd2221603a9472ac4a.js:1:907154
[discord]     at m._dispatch (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:900911)
[discord]     at https://discord.com/assets/e8fd2221603a9472ac4a.js:1:900481
[discord]     at s.log (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:907087)
[discord] [GatewaySocket] [RESET] (true, 1000, Resetting socket due to error.)
[discord] [Flux] Dispatching CONNECTION_CLOSED
[discord] [AuthenticationStore] handleConnectionClosed called with code 1000. [object Object]
[discord] [ConnectionStore] connection closed dispatched
[discord] [GatewaySocket] Setting connection state to WILL_RECONNECT
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
[userscript] Cannot locate Mute/Deafen/Settings button container
`
I tried to reinstall the package via AUR and even tried to compile it myself from the source, same result.

Thanks in advance!</div>

**Comment by xxhinotorixx** [comment]
Sorry, I've just seen that there is already a pull request for this issue. I'm going to close this.
