### ISSUE TITLE
Application struggles to open (ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub)

### ISSUE THREAD

**Issue by reddragonmps** [maltejur/discord-screenaudio#71]
First of all, I really enjoy the app. It is useful and an example that things can work with enough effort. Of course not Discord's effort, anyway. 

My system:
-CPU: Ryzen 5
-GPU: GTX 1060 6GB
-DS: Wayland (I had no problems on X11 this may be a Wayland error)
-DM: KDE
Downloaded from AUR. Tested flatpak and had the same issues.

Sometimes when I open the app I get an `EGL_BAD_CONTEXT` error followed by a Qt error then `GpuChannel` error, then gets stuck in a loop with this three errors.
Other times it just ignores these errors, opens and works perfectly. This are my logs:

`[63116:63153:1109/060735.135815:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[63116:63153:1109/060735.136027:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[63116:63153:1109/060735.136037:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[63116:63153:1109/060735.136042:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[63116:63153:1109/060735.136049:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[63116:63153:1109/060735.136257:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[63116:63153:1109/060735.136266:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[63116:63153:1109/060735.136271:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[63116:63153:1109/060735.136277:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[63116:63153:1109/060735.136540:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[63116:63153:1109/060735.136549:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[63116:63153:1109/060735.136554:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[63116:63153:1109/060735.136560:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub`

When it works:
`[elais@ArchPC ~]$ discord-screenaudio --notify-send
[62726:62763:1109/060550.927621:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060550.927637:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060550.927642:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060550.927647:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[62726:62763:1109/060550.951848:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060550.951876:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060550.951890:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060550.951904:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[main] Injecting  "userscript.js"
[main] Injecting  "version.js"
[main] Injecting  "xmlgui.js"
[main] Injecting  "kglobalaccel.js"
[62726:62763:1109/060551.043083:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060551.043116:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060551.043127:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060551.043141:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[discord] "[FAST CONNECT] connecting to: wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream"
[discord] "[FAST CONNECT] connected in 182ms"
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "%c[default] \nfont-weight: bold;\ncolor: purple;\n [BUILD INFO] Release Channel: stable, Build Number: 157215, Version Hash: f7abf7ee7cd596ac0584c92ed5746423a150fff4"
[discord] "AppCrashedFatalReport: getLastCrash not supported."
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.\nArguments: \n[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 5/13/2022 10:00 -0800, _f: undefined, _strict: undefined, _locale: [object Object]\nError\n    at Function.createFromInputFallback (https://discord.com/assets/d849b17d558beed73072.js:1206:330)\n    at Bn (https://discord.com/assets/d849b17d558beed73072.js:1232:696)\n    at Wn (https://discord.com/assets/d849b17d558beed73072.js:1235:356)\n    at Zn (https://discord.com/assets/d849b17d558beed73072.js:1235:199)\n    at jn (https://discord.com/assets/d849b17d558beed73072.js:1234:886)\n    at Kn (https://discord.com/assets/d849b17d558beed73072.js:1235:697)\n    at zn (https://discord.com/assets/d849b17d558beed73072.js:1235:731)\n    at o (https://discord.com/assets/d849b17d558beed73072.js:1202:961)\n    at Object.918513 (https://discord.com/assets/4b1166ebfc03ebf036e5.js:2233:633)\n    at l (https://discord.com/assets/7ded0cbc8e3366396488.js:1:154)\n    at Object.908570 (https://discord.com/assets/4b1166ebfc03ebf036e5.js:2158:389)\n    at l (https://discord.com/assets/7ded0cbc8e3366396488.js:1:154)\n    at Object.101577 (https://discord.com/assets/4b1166ebfc03ebf036e5.js:224:151)\n    at l (https://discord.com/assets/7ded0cbc8e3366396488.js:1:154)\n    at Object.877271 (https://discord.com/assets/4b1166ebfc03ebf036e5.js:313:283)\n    at l (https://discord.com/assets/7ded0cbc8e3366396488.js:1:154)\n    at Module.402348 (https://discord.com/assets/bbb8d54219a80d2fbc11.js:92:663)\n    at Function.l (https://discord.com/assets/7ded0cbc8e3366396488.js:1:154)"
[62726:62763:1109/060553.076895:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060553.076925:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060553.076948:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060553.076960:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060553.077222:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060553.077235:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060553.077243:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060553.077252:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[discord] "[DEPRECATED] Please use `subscribeWithSelector` middleware"
[discord] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead."
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [CONNECT] wss://gateway.discord.gg, encoding: json, version: 9, compression: zlib-stream"
[discord] "[FAST CONNECT] successfully took over websocket, state: [object Object]"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [CONNECTED] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream in 0 ms"
[discord] "%c[ConnectionStore] \nfont-weight: bold;\ncolor: purple;\n handleIdentify called [object Object]"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [IDENTIFY]"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [HELLO] via \ngateway-prd-us-east1-c-h4vm: 0, heartbeat interval: 41250, took 10 ms"
[62726:62763:1109/060554.163627:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.163644:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.163651:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.163659:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.165474:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.165504:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.165511:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.165520:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.174808:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.174843:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.174849:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.174862:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.175901:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.175915:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.175923:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.175938:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.176518:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.176534:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.176541:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.176551:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.176736:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.176745:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.176750:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.176756:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.177007:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.177017:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.177022:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.177029:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.187075:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.187108:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.187115:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.187125:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[62726:62763:1109/060554.197896:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060554.197924:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060554.197940:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060554.197949:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [READY] took 760ms, as 916742f4d1255414f4438355cf1ea54e via \ngateway-prd-us-east1-c-h4vm: 210.265\n|  id_created: 1.168\n|  session_lookup_time: 0.277\n|  session_lookup_finished: 0.016\n|  discord-sessions-green-prd-2-203: 201.45\n|  |  start_session: 144.079\n|  |  |  discord-api-69f64c5d7b-x9g2j: 127.518\n|  |  |  |  get_user: 17.765\n|  |  |  |  get_guilds: 27.435\n|  |  |  |  user_settings_proto: 0.139\n|  |  |  |  relationships: 36.056\n|  |  |  |  friend_suggestion: 0.074\n|  |  |  |  connections: 0.238\n|  |  |  |  serialized_read_states: 0.01\n|  |  |  |  pending_payments: 0.002\n|  |  |  |  send_scheduled_deletion_message: 0.002\n|  |  |  |  sanitize_premium_perks: 0.001\n|  |  |  |  guild_join_requests: 0.002\n|  |  |  |  user_guild_settings: 0.001\n|  |  |  |  serialized_private_channels: 22.57\n|  |  |  |  experiments: 5.872\n|  |  |  |  affine_user_ids: 0.015\n|  |  |  |  required_action: 0.003\n|  |  |  |  authorized_ip_coro: 0.003\n|  |  starting_guild_connect: 0.038\n|  |  presence_started: 6.47\n|  |  guilds_started: 0.702\n|  |  guilds_connect: 46.398\n|  |  presence_connect: 0.001\n|  |  connect_finished: 46.417\n|  |  build_ready: 2.803\n|  |  optimize_ready: 0.825\n|  |  split_ready: 0.112\n|  |  clean_ready: 0.001"
[discord] "%c[AuthenticationStore] \nfont-weight: bold;\ncolor: purple;\n handleConnectionOpen called [object Object]"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Connecting"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n Added account: reddragonmps"
[62726:62763:1109/060555.277926:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[62726:62763:1109/060555.277964:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[62726:62763:1109/060555.277977:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[62726:62763:1109/060555.277991:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n Updating resume url to wss://gateway-us-east1-c.discord.gg"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [READY_SUPPLEMENTAL] took 1354ms"
[discord] "%c[Flux] \nfont-weight: bold;\ncolor: purple;\n Slow dispatch on GAMES_DATABASE_UPDATE: 238.02999999998065ms"
[discord] "WebSocket connection to 'wss://dealer.spotify.com/?access_token=BQBVc6_9RMEJAUvev5KDJ40dTK0YaLRpqQcm7F2u_fOg8UAkczL0V2yPzsuOtNjPd0wJolHi7b41RrZdHdJyu7MuRPRg05CggCtlpG6CzVMt-Vv7hdQHRMgmz8RgDFGgDMVZ8TeU-nHD9qkzWmV_xzrzpbrYZXUnUElE' failed: HTTP Authentication failed; no valid credentials available"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Disconnected. Next retry in 701ms"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Connecting"
[discord] "WebSocket connection to 'wss://dealer.spotify.com/?access_token=BQBVc6_9RMEJAUvev5KDJ40dTK0YaLRpqQcm7F2u_fOg8UAkczL0V2yPzsuOtNjPd0wJolHi7b41RrZdHdJyu7MuRPRg05CggCtlpG6CzVMt-Vv7hdQHRMgmz8RgDFGgDMVZ8TeU-nHD9qkzWmV_xzrzpbrYZXUnUElE' failed: HTTP Authentication failed; no valid credentials available"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Disconnected. Next retry in 4238ms"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Connecting"
[discord] "WebSocket connection to 'wss://dealer.spotify.com/?access_token=BQBVc6_9RMEJAUvev5KDJ40dTK0YaLRpqQcm7F2u_fOg8UAkczL0V2yPzsuOtNjPd0wJolHi7b41RrZdHdJyu7MuRPRg05CggCtlpG6CzVMt-Vv7hdQHRMgmz8RgDFGgDMVZ8TeU-nHD9qkzWmV_xzrzpbrYZXUnUElE' failed: HTTP Authentication failed; no valid credentials available"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Disconnected. Next retry in 8375ms"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Connecting"
[discord] "WebSocket connection to 'wss://dealer.spotify.com/?access_token=BQBVc6_9RMEJAUvev5KDJ40dTK0YaLRpqQcm7F2u_fOg8UAkczL0V2yPzsuOtNjPd0wJolHi7b41RrZdHdJyu7MuRPRg05CggCtlpG6CzVMt-Vv7hdQHRMgmz8RgDFGgDMVZ8TeU-nHD9qkzWmV_xzrzpbrYZXUnUElE' failed: HTTP Authentication failed; no valid credentials available"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Disconnected. Next retry in 27843ms"
v[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Connecting"
[discord] "WebSocket connection to 'wss://dealer.spotify.com/?access_token=BQBVc6_9RMEJAUvev5KDJ40dTK0YaLRpqQcm7F2u_fOg8UAkczL0V2yPzsuOtNjPd0wJolHi7b41RrZdHdJyu7MuRPRg05CggCtlpG6CzVMt-Vv7hdQHRMgmz8RgDFGgDMVZ8TeU-nHD9qkzWmV_xzrzpbrYZXUnUElE' failed: HTTP Authentication failed; no valid credentials available"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Disconnected. Next retry in 60000ms"`

**Comment by maltejur** [comment]
Hm never seen this error. Maybe outdated graphics drivers or a broken graphics card?

**Comment by reddragonmps** [comment]
My system is up-to-date. I think the main culprit here is Wayland+NVIDIA and not the app itself. Closing this issue because the app still works, it just takes two tries to open.

**Comment by JesusXD88** [comment]
I'm having the same issue as well, GNOME Wayland + NVIDIA too. When launching the app from terminal, the output shows:
`Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.`
I'm running the app through flatpak and it was working fine till some weeks ago, now it's hit or miss, but often fails.

**Comment by reddragonmps** [comment]
Quick update on my case. AUR package seems to work fine as long as you open it twice in quick succesion (not sure why).
Tried flatpak version and surpisingly works as intended. No need to open it twice or anything. I want to point out AUR isn't the latest version. Posting my logs in case there is something of interest: 
`[elais@ArchPC ~]$ flatpak run de.shorsh.discord-screenaudio
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout
[main] Injecting  "userscript.js"
[main] Injecting  "version.js"
[main] Injecting  "xmlgui.js"
[main] Injecting  "kglobalaccel.js"
[default] Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "org.freedesktop.DBus.Error.ServiceUnknown")
[discord] "[FAST CONNECT] connecting to: wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream"
[discord] "[FAST CONNECT] connected in 273ms"
[discord] "%c[default] \nfont-weight: bold;\ncolor: purple;\n [BUILD INFO] Release Channel: stable, Build Number: 160480, Version Hash: f01bfd9942e5569925ee2641c2dc80a2d2c2d194"
[discord] "AppCrashedFatalReport: getLastCrash not supported."
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.\nArguments: \n[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 5/13/2022 10:00 -0800, _f: undefined, _strict: undefined, _locale: [object Object]\nError\n    at Function.createFromInputFallback (https://discord.com/assets/758f6c3f4345f6414752.js:1265:330)\n    at Bn (https://discord.com/assets/758f6c3f4345f6414752.js:1291:696)\n    at Wn (https://discord.com/assets/758f6c3f4345f6414752.js:1294:356)\n    at Zn (https://discord.com/assets/758f6c3f4345f6414752.js:1294:199)\n    at Yn (https://discord.com/assets/758f6c3f4345f6414752.js:1293:886)\n    at Kn (https://discord.com/assets/758f6c3f4345f6414752.js:1294:697)\n    at zn (https://discord.com/assets/758f6c3f4345f6414752.js:1294:731)\n    at o (https://discord.com/assets/758f6c3f4345f6414752.js:1261:961)\n    at Object.918513 (https://discord.com/assets/e489f1a1314d79a76354.js:2325:747)\n    at l (https://discord.com/assets/b6c303106ed1805744cd.js:1:154)\n    at Object.908570 (https://discord.com/assets/e489f1a1314d79a76354.js:2219:794)\n    at l (https://discord.com/assets/b6c303106ed1805744cd.js:1:154)\n    at Object.101577 (https://discord.com/assets/e489f1a1314d79a76354.js:230:188)\n    at l (https://discord.com/assets/b6c303106ed1805744cd.js:1:154)\n    at Object.877271 (https://discord.com/assets/e489f1a1314d79a76354.js:324:101)\n    at l (https://discord.com/assets/b6c303106ed1805744cd.js:1:154)\n    at Module.320907 (https://discord.com/assets/41ecebd78b7fce0e4404.js:93:176)\n    at Function.l (https://discord.com/assets/b6c303106ed1805744cd.js:1:154)"
[discord] "[DEPRECATED] Please use `subscribeWithSelector` middleware"
[discord] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead."
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [CONNECT] wss://gateway.discord.gg, encoding: json, version: 9, compression: zlib-stream"
[discord] "[FAST CONNECT] successfully took over websocket, state: [object Object]"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [CONNECTED] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream in 1 ms"
[discord] "%c[ConnectionStore] \nfont-weight: bold;\ncolor: purple;\n handleIdentify called [object Object]"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [IDENTIFY]"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [HELLO] via \ngateway-prd-us-east1-b-7mmm: 0, heartbeat interval: 41250, took 14 ms"
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [READY] took 565ms, as 950ce35523704860bb12b3e1abc4110c via \ngateway-prd-us-east1-b-7mmm: 178.963\n|  id_created: 2.818\n|  session_lookup_time: 6.491\n|  session_lookup_finished: 0.013\n|  discord-sessions-blue-prd-2-193: 163.376\n|  |  start_session: 125.356\n|  |  |  discord-api-7cd598c96b-rbrpk: 106.32\n|  |  |  |  get_user: 37.158\n|  |  |  |  get_guilds: 18.244\n|  |  |  |  user_settings_proto: 0.096\n|  |  |  |  relationships: 27.843\n|  |  |  |  friend_suggestion: 0.047\n|  |  |  |  connections: 0.148\n|  |  |  |  serialized_read_states: 0.005\n|  |  |  |  pending_payments: 0.001\n|  |  |  |  send_scheduled_deletion_message: 0.001\n|  |  |  |  sanitize_premium_perks: 0.001\n|  |  |  |  guild_join_requests: 0.001\n|  |  |  |  user_guild_settings: 0.001\n|  |  |  |  serialized_private_channels: 5.008\n|  |  |  |  experiments: 3.979\n|  |  |  |  affine_user_ids: 0.01\n|  |  |  |  required_action: 0.003\n|  |  |  |  authorized_ip_coro: 0.001\n|  |  starting_guild_connect: 0.044\n|  |  presence_started: 4.53\n|  |  guilds_started: 0.83\n|  |  guilds_connect: 27.664\n|  |  presence_connect: 0.001\n|  |  connect_finished: 27.682\n|  |  build_ready: 3.983\n|  |  optimize_ready: 0.826\n|  |  split_ready: 0.122\n|  |  clean_ready: 0.001"
[discord] "%c[AuthenticationStore] \nfont-weight: bold;\ncolor: purple;\n handleConnectionOpen called [object Object]"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n WS Connecting"
[discord] "%c[Spotify] \nfont-weight: bold;\ncolor: purple;\n Added account: reddragonmps"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n Updating resume url to wss://gateway-us-east1-b.discord.gg"
[discord] "%c[GatewaySocket] \nfont-weight: bold;\ncolor: purple;\n [READY_SUPPLEMENTAL] took 642ms"
[userscript] Cannot locate Mute/Deafen/Settings button container, please report this on GitHub`

The only thing I've noticed is EGL errors are gone. I have my doubts this is an app problem, more like a dependency one. Maybe an Nvidia problem only.

**Comment by parov0z** [comment]
use `EGL_PLATFORM=surfaceless` to run on nvidia
